# 配置文件定义了玩家右键点击后执行的命令
# 可用变量：
#   %玩家% ——被捉弄者
#  %当前拿着道具的人% ——捉弄者
#  %所有人% ——所有人
第一组:  # 这个是配置的 Lore 组名
  lore:
    - "第一组"  # 第一组对应的Lore内容
  commands:
    - "say %当前拿着道具的人% 用愚人节的棒子愚弄了 %玩家%！"
    - "tell %玩家% 你被 %当前拿着道具的人% 愚弄了！愚人节快乐！"
    - "effect give %玩家% minecraft:slowness 5 1"
    - "effect give %玩家% minecraft:glowing 1 1"

第二组:
  lore:
    - "第二组"
  commands:
    - "say %当前拿着道具的人% 用愚人节棒子愚弄了 %玩家%（第二组）！"
    - "tell %玩家% 你被 %当前拿着道具的人% 愚弄了！（第二组）"
    - "effect give %玩家% minecraft:blindness 5 1"
    - "effect give %玩家% minecraft:levitation 1 1"
