# 配置文件定义了玩家右键点击后执行的命令
commands:
  - "say %当前拿着道具的人% 用愚人节的棒子愚弄了 %玩家%！"
  - "tell %玩家% 你被 %当前拿着道具的人% 愚弄了！愚人节快乐！"
  - "effect give %玩家% minecraft:slowness 5 1"
  - "effect give %玩家% minecraft:glowing 1 1"
  - "say %当前拿着道具的人% 给所有人带来了愚人节的快乐！"
  - "tell %所有人% 大家注意了，%当前拿着道具的人% 正在愚弄所有人！"
  - "say %当前拿着道具的人% 愚弄了 %玩家% ，但是实际是愚弄了自己！"
